/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    DonationPlatform: {
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint256",
              name: "needId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "carrier",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "transitStartTime",
              type: "uint256",
            },
          ],
          name: "DonationInTransit",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint256",
              name: "needId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "donor",
              type: "string",
            },
          ],
          name: "DonationReceived",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint256",
              name: "needId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "donationId",
              type: "uint256",
            },
          ],
          name: "NeedDelivered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "beneficiary",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "requiresTransport",
              type: "bool",
            },
          ],
          name: "NeedRegistered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "NeedVerified",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint256",
              name: "needId",
              type: "uint256",
            },
          ],
          name: "WaitingForPickup",
          type: "event",
        },
        {
          inputs: [],
          name: "admin",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_needId",
              type: "uint256",
            },
          ],
          name: "confirmDelivery",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_needId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "_donor",
              type: "string",
            },
          ],
          name: "donate",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "donations",
          outputs: [
            {
              internalType: "uint256",
              name: "needId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "donor",
              type: "string",
            },
            {
              internalType: "bool",
              name: "delivered",
              type: "bool",
            },
            {
              internalType: "string",
              name: "carrier",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "transitStartTime",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_id",
              type: "uint256",
            },
          ],
          name: "getDonation",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "needId",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "donor",
                  type: "string",
                },
                {
                  internalType: "bool",
                  name: "delivered",
                  type: "bool",
                },
                {
                  internalType: "string",
                  name: "carrier",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "transitStartTime",
                  type: "uint256",
                },
              ],
              internalType: "struct DonationPlatform.Donation",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_id",
              type: "uint256",
            },
          ],
          name: "getDonationStatus",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_id",
              type: "uint256",
            },
          ],
          name: "getNeed",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "id",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "beneficiary",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "description",
                  type: "string",
                },
                {
                  internalType: "enum DonationPlatform.Status",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "bool",
                  name: "requiresTransport",
                  type: "bool",
                },
              ],
              internalType: "struct DonationPlatform.Need",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "needToDonation",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "needs",
          outputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "beneficiary",
              type: "string",
            },
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "enum DonationPlatform.Status",
              name: "status",
              type: "uint8",
            },
            {
              internalType: "bool",
              name: "requiresTransport",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_beneficiary",
              type: "string",
            },
            {
              internalType: "string",
              name: "_description",
              type: "string",
            },
            {
              internalType: "bool",
              name: "_requiresTransport",
              type: "bool",
            },
          ],
          name: "registerNeed",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_needId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "_carrier",
              type: "string",
            },
          ],
          name: "startTransport",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_id",
              type: "uint256",
            },
          ],
          name: "verifyNeed",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
